### PR TITLE
background button

### PR DESCRIPTION
**Pull request by Jashawns**

### CODE REVIEW

**Review by ryanascherr — CHANGES_REQUESTED** [review]
Thanks for doing this!

Button only works to turn off space mode, but won't turn it back on if clicked again.

Also, I was thinking it would be more of a light mode / dark mode, which means the background would be white or something similar, and may require style changes to other parts of the document. But we can make sure the group is on the same page about this.

**Comment by Jashawns** [comment]
> Thanks for doing this!
> 
> Button only works to turn off space mode, but won't turn it back on if clicked again.
> 
> Also, I was thinking it would be more of a light mode / dark mode, which means the background would be white or something similar, and may require style changes to other parts of the document. But we can make sure the group is on the same page about this.

**Comment by Jashawns** [comment]
Ok approve current add and delete branch. I will continue to add the rest and change fonts from white to be able to do a white background and pull another branch

**Review by ryanascherr — APPROVED** [review]

**Comment by ryanascherr** [comment]
> Ok approve current add and delete branch. I will continue to add the rest and change fonts from white to be able to do a white background and pull another branch

Done!

**Pull request merged**
